version: '3'
services:
  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3800:3000"
    depends_on:
      - mongo
    env_file:
      - .env.docker
    command: ["node", "--watch", "./server/index.mjs"]  # Node.js 18+的watch模式

  mongo:
    image: mongo:6.0.6-jammy
    command: ["--wiredTigerCacheSizeGB", "0.25"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    env_file:
      - .env.docker